### ISSUE TITLE
[v1.5.2+ Config Update Bug] - Blast protection config option not being updated to existing config's after update.

### ISSUE THREAD

**Issue by Terminal-Access** [DevCyntrix/death-chest#13]
Death Chest: v1.5.2 and above
Server: PaperMC 1.19.2 Build 232 (any build that support the plugin really)

Upon updating the plugin from a previous version, where a config.yml file has alredy been generated, the plugin failes to update the pre-existing config.yml to include the new "blast protection settings".

**Comment by DevCyntrix** [comment]
Thank you very much for your effort. I already know about that problem but it is difficult to solve because I want that the comments and previous configurations keeps in the configuration file. That's why the newest configuration file is published on SpigotMC if somebody want to use the new features. If I make some huge changes in the configuration file I have the version property in the configuration file so that I can check the version and rename the file to config.yml.old and recreate a new file to avoid a convertion of the file which is edgy and makes the code bad. 

Best regards
Ricardo

**Comment by Terminal-Access** [comment]
Food for thought:

I know the existing issue with using SnakeYaml that it simplly strips all ocmments, there was some one a while back around 2013 that was working on a way to over come that.

Link below:
[Custom Yaml Configurations With Comments](https://bukkit.org/threads/tut-custom-yaml-configurations-with-comments.142592/)

Not sure if t his will help or give you any ideas but it was at best W.I.P.

kind regards
Lee.
